chore: :white_check_mark: add tests to check for correct requirements

diff --git a/Taskfile.yml b/Taskfile.yml
--- a/Taskfile.yml
+++ b/Taskfile.yml
@@ -7,6 +7,7 @@ vars:
 
 tasks:
   build:
+    aliases: [ b ]
     desc: Build the 5min-idp image
     cmds:
       - docker buildx build --platform {{.PLATFORM}} -t {{.IMG}} .
@@ -15,33 +16,55 @@ tasks:
       - docker buildx build -t {{.IMG}} --load .
 
   check-image:
+    aliases: [ ci ]
     desc: Check the 5min-idp image
     cmds:
       - docker run --rm -v {{.PWD}}:/app {{.IMG}} ./image/check.sh
 
+  kind-export-kubeconfig:
+    aliases: [ kek ]
+    desc: Export the kubeconfig for the kind cluster
+    cmds:
+      - kind export kubeconfig --name 5min-idp
+
   push:
+    aliases: [ p ]
     desc: Push the 5min-idp image
     cmds:
       - docker buildx build --platform {{.PLATFORM}} -t {{.IMG}} --push .
 
   lint-init:
+    aliases: [ li ]
     desc: Initialize tflint
     cmds:
       - tflint --init
 
   lint:
+    aliases: [ l ]
     desc: Lint terraform directory
     deps: [ lint-init ]
     cmds:
       - tflint --config ../.tflint.hcl --chdir=./setup/terraform
 
+  check-env:
+    internal: true
+    cmds:
+      - |
+        if [ -z "$HUMANITEC_ORG" ]; then
+          echo -e "\033[0;31mError: HUMANITEC_ORG environment variable is not set\033[0m"
+          exit 1
+        else
+          echo -e "\033[0;32m✓ HUMANITEC_ORG is set\033[0m"
+        fi
+
   test:
+    aliases: [ t ]
     desc: Test the 5min-idp
-    deps: [ build, check-image ]
+    deps: [ build, check-image, check-env ]
     cmds:
       - |
         docker run --rm -i -h 5min-idp --name 5min-idp \
-          -e HUMANITEC_ORG \
+          -e HUMANITEC_ORG=${HUMANITEC_ORG} \
           -v hum-5min-idp:/state \
           -v $HOME/.humctl:/root/.humctl \
           -v /var/run/docker.sock:/var/run/docker.sock \
@@ -49,12 +72,13 @@ tasks:
           {{.IMG}} ./image/test.sh
 
   run-local:
+    aliases: [ r, run ]
     desc: Run the locally built image
-    deps: [ build ]
+    deps: [ build, check-env ]
     cmds:
       - |
         docker run --rm -it -h 5min-idp --name 5min-idp \
-          -e HUMANITEC_ORG \
+          -e HUMANITEC_ORG=${HUMANITEC_ORG} \
           -v hum-5min-idp:/state \
           -v $HOME/.humctl:/root/.humctl \
           -v /var/run/docker.sock:/var/run/docker.sock \
